#parameters:

services:
    cube_common.project_version:
        class: CubeTools\CubeCommonBundle\Project\ProjectVersionGit
        arguments:
            - %kernel.root_dir%
            - %kernel.cache_dir%
    cube_common.file_excel:
        class: CubeTools\CubeCommonBundle\FileFormat\ExcelFile
        calls:
            - [setExcelService, ['@?phpexcel']]
